const translations = {
  "en": {
    "skip": "Skip to content",
    "navProject": "Project",
    "navQuestions": "Questions",
    "navApproach": "Approach",
    "navAbout": "About",
    "navContact": "Contact",
    "heroEyebrow": "Independent documentary project · Research & pre-production",
    "heroTitle": "Japan Through Bathing Culture",
    "heroStatement": "Exploring Japan’s bathing culture through the people, places and crafts that shape it.",
    "heroIntro": "From neighbourhood sentō and hot springs to ryokan, architecture, art and everyday rituals, the project explores how bathing culture developed, how it is lived today, and how it continues to change over time.",
    "heroCta": "Discover the project",
    "projectEyebrow": "The project",
    "projectTitle": "A culture of bathing. A way of exploring Japan.",
    "projectP1": "Bathing in Japan is more than a single practice or type of place. It connects public baths, hot springs and inns with everyday routines, etiquette, hospitality, communities, history and the people whose work makes these spaces possible.",
    "projectP2": "This documentary project starts with the bath and follows those connections outward. I want to understand how these practices developed, what they mean to different people today, and how they are continued, adapted or reinterpreted over time.",
    "projectP3": "The bath also opens onto a wider material world: murals, architecture, woodwork, ceramics, tableware, textiles, gardens, food and seasonal decoration. These details are not simply aesthetic. They can reveal the skills, choices and relationships that shape the places in which bathing culture exists.",
    "projectQuote": "The aim is not to arrive with a definition of what Japanese bathing culture “really is”. It is to listen to the people who live, work and create around it, and allow their perspectives to shape the episodes.",
    "worldEyebrow": "The world around the bath",
    "worldTitle": "One subject, many connected worlds.",
    "worldIntro": "The bath is the starting point, but rarely the whole story. Each place is shaped by the people who use and maintain it, the objects and skills around it, and the choices made over time. These are the connections the project follows.",
    "worldBathTitle": "Bath",
    "worldBathText": "The gestures, rules and sensations of bathing — and what they reveal about comfort, privacy and being together.",
    "worldPeopleTitle": "People",
    "worldPeopleText": "The people who bathe, welcome, clean, repair, manage and return — each with a different relationship to the same place.",
    "worldPlacesTitle": "Places",
    "worldPlacesText": "A neighbourhood sentō, mountain onsen or family ryokan can shape very different kinds of everyday life and encounter.",
    "worldMakingTitle": "Making",
    "worldMakingText": "The things around the bath are made by someone. Following them can uncover craft, labour and decisions usually hidden from the guest.",
    "worldTimeTitle": "Time",
    "worldTimeText": "What continues because it still works? What changes because people need it to? History becomes visible through those everyday choices.",
    "questionsEyebrow": "Questions we are exploring",
    "questionsTitle": "A working map, not a fixed programme.",
    "questionsIntro": "The project is currently being researched as a series of independent episodes of roughly 20–25 minutes. These are working questions rather than a fixed programme: the final stories will depend on the people we meet, what we learn and the access available.",
    "q1Title": "Why Japan Bathes",
    "q1Question": "How did bathing acquire meanings beyond washing, and how can those histories still be understood today?",
    "q1Detail": "Rather than treating bathing as a timeless national habit, trace how ideas about cleanliness, healing, religion and shared water met — and changed.",
    "q2Title": "The Public Bath",
    "q2Question": "What place does a neighbourhood sentō hold in contemporary life?",
    "q2Detail": "If most homes have baths, why keep going to the sentō? The answer may lie as much in routine, ownership and neighbourhood life as in the water.",
    "q3Title": "The Journey to the Hot Spring",
    "q3Question": "How has travelling to hot springs changed — and how have onsen destinations changed with it?",
    "q3Detail": "From long therapeutic stays to short leisure trips, changing reasons for travelling to hot springs also change what towns must become for visitors — and residents.",
    "q4Title": "The Inn",
    "q4Question": "What makes ryokan hospitality possible every day?",
    "q4Detail": "Hospitality is visible to the guest; the labour behind it usually is not. Follow the people and decisions that make the experience possible each day.",
    "q5Title": "The Hands Around the Bath",
    "q5Question": "What can the things surrounding bathing tell us about the culture itself?",
    "q5Detail": "A mural, bathhouse tile or wooden fitting becomes more interesting when we can follow the maker, the commission and the place where it is actually used.",
    "q6Title": "Continuity and Change",
    "q6Question": "What do people choose to continue, adapt, reinterpret — or leave behind?",
    "q6Detail": "Continuity is not automatic — and change is not necessarily loss. Ask the people involved what deserves effort, what no longer fits, and who gets to decide.",
    "approachEyebrow": "Approach",
    "approachTitle": "Listening before explaining.",
    "approachIntro": "I am approaching this project as a curious observer rather than as an expert arriving with a conclusion. Research gives me questions, but the people I meet should be able to challenge those questions, contradict my assumptions and point the project somewhere unexpected.",
    "approachIntro2": "Whenever possible, the episodes will favour observation over explanation: following people at work, watching how places function and connecting history to real objects, routines and spaces in the present.",
    "interludeEyebrow": "Short contextual interludes",
    "interludeTitle": "History, belief and folklore — when they illuminate the present.",
    "interludeText": "Between observational sequences, short segments can connect a place, object or practice to a historical episode, local story, belief or material tradition. They are not decorative detours: each one should be sourced and anchored to something we can still see in the episode today.",
    "p1Title": "People before themes",
    "p1Text": "Start with specific experiences rather than using people to illustrate a predetermined idea.",
    "p2Title": "Questions before conclusions",
    "p2Text": "Treat preservation, change, tourism, community and tradition as things to investigate rather than positions to defend.",
    "p3Title": "Context before spectacle",
    "p3Text": "Avoid exoticising, romanticising or looking for shock effects.",
    "p4Title": "Respect before access",
    "p4Text": "Private spaces, bathing spaces and identifiable people are filmed only with appropriate permission and consent.",
    "statusEyebrow": "Where the project is now",
    "statusTitle": "A project in development.",
    "novDate": "November 2026",
    "novTitle": "Reconnaissance",
    "novText": "A trip already planned in Japan will be used selectively for location scouting, visual research, ambient sound, filming practice and informal encounters. It is not principal photography.",
    "febDate": "23 February–10 March 2027",
    "febTitle": "Possible principal photography",
    "febText": "A dedicated production trip beginning in Tokyo and then focusing on a small number of stories and locations where meaningful access has developed. Japanese interviews would be conducted with professional language support where necessary.",
    "statusNote": "The project is intentionally still open. Locations, participants and even some of the questions may change as the research develops.",
    "aboutEyebrow": "About the filmmaker",
    "aboutTitleLine1": "Research first.",
    "aboutTitleLine2": "Film with care.",
    "aboutP1": "I’m Arnaud, a French designer and researcher developing this documentary project independently.",
    "aboutP2": "For more than ten years, my professional work has involved behavioural and qualitative research applied to user experience — observing how people behave, listening to their experiences, asking questions and testing assumptions rather than beginning with an answer.",
    "aboutP3": "Documentary filmmaking is a newer practice for me, but that research mindset strongly shapes the way I approach this project: with curiosity, care and a willingness to let the people I meet challenge my initial understanding.",
    "aboutP4": "My interest in Japan has developed over many years, and this project comes from a desire to look beyond destinations themselves — toward the people, work, customs, objects and relationships that give places their meaning.",
    "aboutP5": "I am currently developing and funding the project independently, with the intention of first making the strongest episodes I can before deciding how the project should grow.",
    "closingEyebrow": "An open invitation",
    "closingTitle": "Help me understand it better.",
    "closingText": "The project is still taking shape, and conversations are part of the research. I would be very interested in hearing from people who work with, study, maintain, use or create around Japanese bathing culture. Perspectives that challenge, refine or broaden my current understanding are especially valuable.",
    "closingNote": "Suggestions of people, places, research or stories are equally welcome. Contact details will be added before the first outreach.",
    "footerText": "Independent documentary project in development",
    "backTop": "Back to top"
  },
  "fr": {
    "skip": "Aller au contenu",
    "navProject": "Projet",
    "navQuestions": "Questions",
    "navApproach": "Approche",
    "navAbout": "À propos",
    "navContact": "Contact",
    "heroEyebrow": "Projet documentaire indépendant · Recherche & préproduction",
    "heroTitle": "Le Japon à travers sa culture du bain",
    "heroStatement": "Explorer la culture japonaise du bain à travers les personnes, les lieux et les savoir-faire qui la façonnent.",
    "heroIntro": "Des sentō de quartier et des sources chaudes aux ryokan, à l’architecture, à l’art et aux rituels du quotidien, le projet cherche à comprendre comment la culture du bain s’est construite, comment elle est vécue aujourd’hui et comment elle continue d’évoluer.",
    "heroCta": "Découvrir le projet",
    "projectEyebrow": "Le projet",
    "projectTitle": "Une culture du bain. Une manière d’explorer le Japon.",
    "projectP1": "Au Japon, le bain ne se résume pas à une pratique ou à un type de lieu. Il relie bains publics, sources chaudes et auberges à des habitudes quotidiennes, des règles de savoir-vivre, l’hospitalité, la vie locale, l’histoire et au travail de celles et ceux qui font vivre ces espaces.",
    "projectP2": "Le projet part du bain pour suivre ces liens vers l’extérieur. Je cherche à comprendre comment ces pratiques se sont construites, ce qu’elles signifient aujourd’hui pour différentes personnes et comment elles sont transmises, adaptées ou réinterprétées au fil du temps.",
    "projectP3": "Le bain ouvre aussi sur tout un univers matériel : peintures murales, architecture, travail du bois, céramique, vaisselle, textiles, jardins, cuisine et décorations saisonnières. Ces détails ne sont pas seulement esthétiques : ils peuvent révéler les savoir-faire, les choix et les relations qui façonnent ces lieux.",
    "projectQuote": "L’objectif n’est pas d’arriver avec une définition de ce qu’est « vraiment » la culture japonaise du bain. Il s’agit d’écouter les personnes qui y vivent, y travaillent ou créent autour d’elle, et de laisser leurs points de vue façonner les épisodes.",
    "worldEyebrow": "Le monde autour du bain",
    "worldTitle": "Un sujet, plusieurs mondes reliés.",
    "worldIntro": "Le bain est le point de départ, mais rarement toute l’histoire. Chaque lieu est façonné par celles et ceux qui l’utilisent et l’entretiennent, par les objets et savoir-faire qui l’entourent, et par les choix faits au fil du temps. Ce sont ces liens que le projet cherche à suivre.",
    "worldBathTitle": "Le bain",
    "worldBathText": "Les gestes, les règles et les sensations du bain — et ce qu’ils disent du confort, de l’intimité et du fait d’être ensemble.",
    "worldPeopleTitle": "Les personnes",
    "worldPeopleText": "Celles et ceux qui se baignent, accueillent, nettoient, réparent, gèrent ou reviennent — chacun entretient une relation différente avec un même lieu.",
    "worldPlacesTitle": "Les lieux",
    "worldPlacesText": "Un sentō de quartier, un onsen de montagne ou un ryokan familial peuvent produire des expériences très différentes du quotidien et de la rencontre.",
    "worldMakingTitle": "Les savoir-faire",
    "worldMakingText": "Les objets qui entourent le bain sont fabriqués par quelqu’un. Les suivre permet de révéler des savoir-faire, du travail et des choix souvent invisibles pour le visiteur.",
    "worldTimeTitle": "Le temps",
    "worldTimeText": "Qu’est-ce qui continue parce que cela fonctionne encore ? Qu’est-ce qui change parce que les besoins évoluent ? L’histoire devient visible dans ces décisions quotidiennes.",
    "questionsEyebrow": "Les questions que nous explorons",
    "questionsTitle": "Une carte de travail, pas un programme figé.",
    "questionsIntro": "Le projet est actuellement développé comme une série d’épisodes indépendants d’environ 20 à 25 minutes. Il s’agit de questions de travail, pas d’un programme arrêté : les histoires finales dépendront des personnes rencontrées, de ce que nous apprendrons et des accès possibles.",
    "q1Title": "Pourquoi le Japon se baigne",
    "q1Question": "Comment le bain a-t-il pris des significations qui dépassent l’hygiène, et comment peut-on encore comprendre ces histoires aujourd’hui ?",
    "q1Detail": "Plutôt que de traiter le bain comme une habitude nationale intemporelle, suivre la façon dont propreté, soin, religion et bain collectif se sont rencontrés — puis transformés.",
    "q2Title": "Le bain public",
    "q2Question": "Quelle place un sentō de quartier occupe-t-il encore dans la vie contemporaine ?",
    "q2Detail": "Si la plupart des foyers ont une salle de bain, pourquoi continuer à aller au sentō ? La réponse se trouve peut-être autant dans les habitudes, le travail des propriétaires et la vie du quartier que dans l’eau.",
    "q3Title": "Le voyage aux sources chaudes",
    "q3Question": "Comment le voyage vers les sources chaudes a-t-il changé — et comment les destinations thermales ont-elles changé avec lui ?",
    "q3Detail": "Des longs séjours thérapeutiques aux escapades de loisir, les raisons de voyager vers les sources chaudes changent — et avec elles ce que les villes thermales doivent devenir pour les visiteurs comme pour les habitants.",
    "q4Title": "L’auberge",
    "q4Question": "Qu’est-ce qui rend l’hospitalité d’un ryokan possible chaque jour ?",
    "q4Detail": "L’hospitalité est visible pour le client ; le travail qui la rend possible l’est beaucoup moins. Suivre les personnes et les décisions qui fabriquent cette expérience chaque jour.",
    "q5Title": "Les mains autour du bain",
    "q5Question": "Que peuvent nous apprendre les objets et les savoir-faire qui entourent le bain ?",
    "q5Detail": "Une peinture murale, un carreau de bain ou une pièce de bois devient plus intéressante quand on peut suivre l’artisan, la commande et le lieu où l’objet est réellement utilisé.",
    "q6Title": "Continuité et changement",
    "q6Question": "Que choisit-on de transmettre, d’adapter, de réinterpréter — ou de laisser derrière soi ?",
    "q6Detail": "La continuité n’est pas automatique — et le changement n’est pas nécessairement une perte. Demander aux personnes concernées ce qui mérite un effort, ce qui ne convient plus, et qui décide.",
    "approachEyebrow": "Approche",
    "approachTitle": "Écouter avant d’expliquer.",
    "approachIntro": "J’aborde ce projet comme un observateur curieux, pas comme un expert arrivant avec une conclusion. La recherche me donne des questions, mais les personnes rencontrées doivent pouvoir les remettre en cause, contredire mes hypothèses et emmener le projet dans une direction inattendue.",
    "approachIntro2": "Autant que possible, les épisodes privilégieront l’observation à l’explication : suivre les personnes dans leur travail, regarder comment les lieux fonctionnent et relier l’histoire à des objets, des gestes et des espaces bien réels aujourd’hui.",
    "interludeEyebrow": "Courtes parenthèses de contexte",
    "interludeTitle": "Histoire, croyances et folklore — lorsqu’ils éclairent le présent.",
    "interludeText": "Entre deux séquences d’observation, de courts segments pourront relier un lieu, un objet ou une pratique à un épisode historique, un récit local, une croyance ou une tradition matérielle. Il ne s’agit pas de détours décoratifs : chaque parenthèse devra être sourcée et rattachée à quelque chose que l’on peut encore observer aujourd’hui.",
    "p1Title": "Les personnes avant les thèmes",
    "p1Text": "Partir d’expériences concrètes plutôt que d’utiliser les gens pour illustrer une idée déjà décidée.",
    "p2Title": "Les questions avant les conclusions",
    "p2Text": "Considérer préservation, changement, tourisme, communauté et tradition comme des sujets à explorer, pas comme des positions à défendre.",
    "p3Title": "Le contexte avant le spectacle",
    "p3Text": "Éviter l’exotisation, la romantisation ou la recherche de l’effet choc.",
    "p4Title": "Le respect avant l’accès",
    "p4Text": "Les espaces privés, les espaces de bain et les personnes identifiables ne sont filmés qu’avec les autorisations et consentements appropriés.",
    "statusEyebrow": "Où en est le projet",
    "statusTitle": "Un projet en développement.",
    "novDate": "Novembre 2026",
    "novTitle": "Repérages",
    "novText": "Un voyage déjà prévu au Japon sera utilisé de manière sélective pour des repérages, de la recherche visuelle, du son d’ambiance, de la pratique de tournage et des rencontres informelles. Ce n’est pas encore le tournage principal.",
    "febDate": "23 février–10 mars 2027",
    "febTitle": "Tournage principal envisagé",
    "febText": "Un voyage de production dédié, commençant à Tokyo puis se concentrant sur un petit nombre d’histoires et de lieux où un accès pertinent aura pu être construit. Les entretiens en japonais se feront avec un accompagnement linguistique professionnel lorsque nécessaire.",
    "statusNote": "Le projet reste volontairement ouvert. Les lieux, les participants et même certaines questions pourront évoluer au fil de la recherche.",
    "aboutEyebrow": "À propos du réalisateur",
    "aboutTitleLine1": "La recherche d’abord.",
    "aboutTitleLine2": "Filmer avec attention.",
    "aboutP1": "Je m’appelle Arnaud. Je suis designer et chercheur français et je développe ce projet documentaire de manière indépendante.",
    "aboutP2": "Depuis plus de dix ans, mon travail professionnel implique de la recherche comportementale et qualitative appliquée à l’expérience utilisateur : observer les comportements, écouter les expériences, poser des questions et tester des hypothèses plutôt que partir d’une réponse.",
    "aboutP3": "La réalisation documentaire est une pratique plus récente pour moi, mais cette culture de la recherche façonne directement mon approche du projet : avec curiosité, attention et la volonté de laisser les personnes rencontrées remettre en question ma compréhension initiale.",
    "aboutP4": "Mon intérêt pour le Japon s’est construit au fil de nombreuses années. Ce projet vient du désir de regarder au-delà des destinations elles-mêmes — vers les personnes, le travail, les usages, les objets et les relations qui donnent du sens aux lieux.",
    "aboutP5": "Je développe et finance actuellement le projet de manière indépendante, avec l’intention de réaliser d’abord les épisodes les plus solides possibles avant de décider comment le projet pourra grandir.",
    "closingEyebrow": "Une invitation ouverte",
    "closingTitle": "Aidez-moi à mieux comprendre.",
    "closingText": "Le projet est encore en construction, et les conversations font partie de la recherche. Je serais très heureux d’échanger avec des personnes qui travaillent, étudient, entretiennent, utilisent ou créent autour de la culture japonaise du bain. Les points de vue qui remettent en question, affinent ou élargissent ma compréhension actuelle sont particulièrement précieux.",
    "closingNote": "Les suggestions de personnes, de lieux, de recherches ou d’histoires sont tout aussi bienvenues. Les coordonnées seront ajoutées avant les premiers contacts.",
    "footerText": "Projet documentaire indépendant en développement",
    "backTop": "Retour en haut"
  },
  "ja": {
    "skip": "本文へ移動",
    "navProject": "企画",
    "navQuestions": "問い",
    "navApproach": "取材姿勢",
    "navAbout": "制作者",
    "navContact": "連絡",
    "heroEyebrow": "自主制作ドキュメンタリー · リサーチ／プリプロダクション",
    "heroTitle": "日本の入浴文化を通して見る暮らし",
    "heroStatement": "人、場所、手仕事を通して、日本の入浴文化を見つめる。",
    "heroIntro": "まちの銭湯や温泉、旅館から、建築、芸術、日々の習慣まで。入浴文化がどのように形づくられ、現在どのように暮らしの中に存在し、時間とともにどう変化しているのかを探るドキュメンタリー企画です。",
    "heroCta": "企画を見る",
    "projectEyebrow": "企画について",
    "projectTitle": "入浴文化から、日本を見つめる。",
    "projectP1": "日本の入浴は、ひとつの習慣や場所だけでは語れません。銭湯、温泉、旅館は、日々の暮らし、作法、おもてなし、地域社会、歴史、そしてそれらの場所を支える人々の仕事とつながっています。",
    "projectP2": "この企画では、まず「風呂」を入り口にし、そこから広がるつながりを追っていきます。入浴の文化がどのように形づくられてきたのか、今どのように受け止められているのか、そして何が受け継がれ、変えられ、あるいは新しく解釈されているのかを知りたいと考えています。",
    "projectP3": "入浴文化は、銭湯絵、建築、木工、器、漆器、布、庭、料理、季節のしつらえといった幅広い物質文化にもつながっています。これらは単なる美しい装飾ではなく、その場所を形づくる技術、選択、人間関係を知る手がかりでもあります。",
    "projectQuote": "最初から「日本の入浴文化とはこういうものだ」と決めつけるのではなく、そこで暮らし、働き、つくる方々の声を聞き、その視点によってエピソードそのものを形づくっていきたいと考えています。",
    "worldEyebrow": "風呂を取り巻く世界",
    "worldTitle": "ひとつのテーマから、いくつもの世界へ。",
    "worldIntro": "風呂は出発点ですが、物語のすべてではありません。ひとつの場所は、利用する人、支える人、そこにある物や技術、そして時間の中で重ねられてきた選択によって形づくられています。この企画では、そのつながりをたどります。",
    "worldBathTitle": "風呂",
    "worldBathText": "入浴の動作、作法、感覚を見つめながら、心地よさ、プライバシー、人と一緒に過ごすことについて何が見えてくるのかを探ります。",
    "worldPeopleTitle": "人",
    "worldPeopleText": "入る人、迎える人、掃除する人、直す人、経営する人、通い続ける人。同じ場所との関係は人によって異なります。",
    "worldPlacesTitle": "場所",
    "worldPlacesText": "まちの銭湯、山の温泉、家族経営の旅館。それぞれの場所は、日常や人との出会い方を違った形でつくります。",
    "worldMakingTitle": "手仕事",
    "worldMakingText": "風呂の周りにある物は、誰かがつくったものです。つくり手や使われる場所を追うことで、客からは見えにくい技術、仕事、判断が見えてきます。",
    "worldTimeTitle": "時間",
    "worldTimeText": "今も役に立つから続くものは何か。必要が変わったから変わるものは何か。日々の選択の中に歴史が現れます。",
    "questionsEyebrow": "いま考えている問い",
    "questionsTitle": "完成した番組表ではなく、取材のための地図。",
    "questionsIntro": "現時点では、20〜25分程度の独立したエピソードを複数制作する構想です。以下は確定したエピソードではなく、取材を通して確かめたい問いです。実際の物語は、出会う方々、学んだこと、撮影できる範囲によって変わります。",
    "q1Title": "日本と入浴",
    "q1Question": "入浴は、清潔さを超えてどのような意味を持つようになったのか。その歴史を今どのように理解できるのか。",
    "q1Detail": "入浴を「昔から変わらない日本の習慣」として扱うのではなく、清潔、癒やし、宗教、共同浴場といった考えがどのように重なり、変化してきたのかをたどります。",
    "q2Title": "まちの銭湯",
    "q2Question": "現代の暮らしの中で、まちの銭湯はどんな場所なのか。",
    "q2Detail": "多くの家に風呂がある今、なぜ銭湯に通い続けるのか。答えは湯そのものだけでなく、習慣、経営する人の仕事、地域との関係にもあるかもしれません。",
    "q3Title": "温泉への旅",
    "q3Question": "温泉への旅はどう変わり、温泉地はその変化とどう向き合ってきたのか。",
    "q3Detail": "長期の湯治から短い観光旅行まで、温泉へ行く理由が変われば、温泉地に求められるものも変わります。訪れる人と暮らす人の双方から、その変化を見ます。",
    "q4Title": "旅館の日々",
    "q4Question": "旅館のおもてなしは、毎日どのような仕事によって成り立っているのか。",
    "q4Detail": "宿泊客には「おもてなし」が見えますが、それを支える仕事はほとんど見えません。毎日の体験を成立させる人と判断を追います。",
    "q5Title": "湯を支える手仕事",
    "q5Question": "風呂の周りにあるものから、その文化について何が見えてくるのか。",
    "q5Detail": "銭湯絵、タイル、木の造作も、つくり手、依頼した人、実際に使われる場所まで追うと、単なる装飾以上の物語が見えてきます。",
    "q6Title": "受け継ぐもの、変わるもの",
    "q6Question": "人々は何を受け継ぎ、何を変え、何を新しく解釈し、あるいは手放すのか。",
    "q6Detail": "続くことは自動的ではなく、変わることが必ずしも喪失でもありません。何を残す価値があるのか、何がもう合わないのか、そして誰が決めるのかを当事者に聞きます。",
    "approachEyebrow": "取材姿勢",
    "approachTitle": "説明する前に、まず聞く。",
    "approachIntro": "私は、結論を持った専門家としてではなく、知りたいことを持った観察者としてこの企画に向き合っています。リサーチは問いを与えてくれますが、実際に出会う方々には、その問い自体を疑い、私の思い込みを否定し、企画を思いがけない方向へ導いてほしいと考えています。",
    "approachIntro2": "できる限り、説明よりも観察を重視します。仕事をする人を追い、場所がどのように機能しているかを見つめ、歴史を、現在そこにある物、動作、空間へとつなげていきます。",
    "interludeEyebrow": "短い文化的な補足",
    "interludeTitle": "歴史、信仰、民間伝承——今を理解する助けになるときに。",
    "interludeText": "観察の場面の合間に、場所、物、習慣を、歴史上の出来事、地域の語り、信仰、ものづくりの伝統へとつなぐ短い補足を入れることがあります。単なる雰囲気づくりではなく、根拠を確認し、現在の映像の中で実際に見えるものと結びつけます。",
    "p1Title": "テーマより人から始める",
    "p1Text": "あらかじめ決めた考えを人に説明してもらうのではなく、具体的な経験から始める。",
    "p2Title": "結論より問いを大切にする",
    "p2Text": "保存、変化、観光、地域、伝統を、守るべき立場としてではなく調べるべき問いとして扱う。",
    "p3Title": "見世物より文脈を大切にする",
    "p3Text": "異国情緒を強調したり、過度に美化したり、刺激的な演出を目的にしない。",
    "p4Title": "アクセスより敬意を優先する",
    "p4Text": "私有地、浴場、個人が特定できる撮影は、必要な許可と同意を得たうえで行う。",
    "statusEyebrow": "現在の段階",
    "statusTitle": "まだ発展途中の企画です。",
    "novDate": "2026年11月",
    "novTitle": "ロケハン／リサーチ",
    "novText": "すでに予定している日本旅行の一部を、候補地の下見、映像リサーチ、環境音の収録、撮影練習、そして非公式な出会いに使う予定です。本撮影ではありません。",
    "febDate": "2027年2月23日〜3月10日",
    "febTitle": "本撮影候補期間",
    "febText": "東京から始まり、その後、意味のある物語と撮影機会が見えてきた少数の場所に絞る専用の撮影旅行を検討しています。日本語のインタビューには必要に応じて専門的な通訳・言語サポートを依頼します。",
    "statusNote": "この企画は意図的にまだ開かれています。リサーチが進むにつれ、場所、参加者、そして問いそのものが変わる可能性があります。",
    "aboutEyebrow": "制作者について",
    "aboutTitleLine1": "まず調べる。",
    "aboutTitleLine2": "そして丁寧に撮る。",
    "aboutP1": "私はアルノーです。フランス出身のデザイナー／リサーチャーとして、このドキュメンタリー企画を個人で進めています。",
    "aboutP2": "10年以上にわたり、ユーザー体験の分野で行動リサーチや定性調査に携わってきました。人の行動を観察し、経験を聞き、問いを立て、最初から答えを決めずに仮説を検証する仕事です。",
    "aboutP3": "ドキュメンタリー制作は私にとってより新しい実践ですが、このリサーチの姿勢は企画への向き合い方に強く影響しています。好奇心と配慮を持ち、出会う方々によって自分の最初の理解が変わることを大切にしています。",
    "aboutP4": "日本への関心は長い時間をかけて育ってきました。この企画は、観光地そのものだけでなく、その場所に意味を与える人々、仕事、習慣、物、関係性を見つめたいという思いから生まれました。",
    "aboutP5": "現在は個人で企画と資金を進めています。まずできる限り良いエピソードをつくり、その後で企画をどのように発展させるかを考えるつもりです。",
    "closingEyebrow": "開かれたお願い",
    "closingTitle": "もっと深く理解するために。",
    "closingText": "この企画はまだ形づくられている途中であり、対話そのものがリサーチの一部です。日本の入浴文化に関わって働く方、研究する方、維持する方、利用する方、ものをつくる方のお話をぜひ伺いたいと考えています。現在の理解を問い直し、より正確にし、広げてくれる視点は特に大切です。",
    "closingNote": "人、場所、研究、物語についてのご提案も歓迎しています。最初の連絡を行う前に、ここへ連絡先を追加します。",
    "footerText": "制作準備中の自主ドキュメンタリー企画",
    "backTop": "ページ上部へ"
  }
};

const supported = ['en','fr','ja'];

function resolveLanguage(){
  const params = new URLSearchParams(location.search);
  const urlLang = params.get('lang');
  const stored = localStorage.getItem('bath-doc-lang');
  const browser = (navigator.languages?.[0] || navigator.language || 'en').toLowerCase();
  const browserLang = browser.startsWith('fr') ? 'fr' : browser.startsWith('ja') ? 'ja' : 'en';
  return supported.includes(urlLang) ? urlLang : supported.includes(stored) ? stored : browserLang;
}

function applyLanguage(lang, persist=false){
  if(!supported.includes(lang)) lang='en';
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el=>{
    const key = el.dataset.i18n;
    if(translations[lang][key]) el.textContent = translations[lang][key];
  });
  document.querySelectorAll('[data-lang]').forEach(btn=>{
    btn.setAttribute('aria-pressed', String(btn.dataset.lang === lang));
  });
  if(persist) localStorage.setItem('bath-doc-lang', lang);
  const title = translations[lang].heroTitle;
  document.title = `${title} — ${translations[lang].footerText}`;
  const description = translations[lang].heroStatement;
  document.querySelector('meta[name="description"]')?.setAttribute('content', description);
  document.querySelector('meta[property="og:title"]')?.setAttribute('content', title);
  document.querySelector('meta[property="og:description"]')?.setAttribute('content', description);
}

document.querySelectorAll('[data-lang]').forEach(btn=>{
  btn.addEventListener('click', ()=>{
    const lang = btn.dataset.lang;
    applyLanguage(lang, true);
    const url = new URL(location.href);
    url.searchParams.set('lang', lang);
    history.replaceState({}, '', url);
  });
});

applyLanguage(resolveLanguage());


const backToTop = document.querySelector('.back-to-top');
if (backToTop) {
  const updateBackToTop = () => {
    backToTop.classList.toggle('is-visible', window.scrollY > 120);
  };

  updateBackToTop();
  window.addEventListener('scroll', updateBackToTop, { passive: true });
}
